# Generated by Django 5.1 on 2024-09-30 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('es_favorito', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_familia', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEscolaridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('codigo', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('codigo', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('codigo', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('codigo', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoParentesco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('codigo', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProfesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('codigo', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('codigo', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('n_documento', models.CharField(max_length=10, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('escolaridad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tipoescolaridad')),
                ('estadoCivil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tipoestadocivil')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tipogenero')),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tipoidentificacion')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.localidad')),
                ('profesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tipoprofesion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.zona')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.familia')),
                ('parentesco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tipoparentesco')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='localidad',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.zona'),
        ),
        migrations.CreateModel(
            name='UsuarioEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asistencia', models.DateField()),
                ('asistencia', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'evento', 'fecha_asistencia')},
            },
        ),
    ]
